In [7]:
import numpy as np

a = np.array([1,2,3])
print(a)

[1 2 3]


In [8]:
import numpy as np

a  = np.array([[1,2,3],[4,5,6]])
print(a)

[[1 2 3]
 [4 5 6]]


In [9]:
import numpy as np
a = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(a)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [10]:
import numpy as np
np.array([1,2,3],dtype=bool)

array([ True,  True,  True])

In [11]:
import numpy as np
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [12]:
import numpy as np
np.arange(1,11).reshape(5,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [13]:
#np.ones and np.zeros
import numpy as np
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [14]:
import numpy as np
np.random.random((3,4))

array([[0.82554429, 0.49538357, 0.91821587, 0.72560738],
       [0.55731173, 0.64230784, 0.88775038, 0.75641171],
       [0.66011176, 0.75825408, 0.56759475, 0.28787727]])

In [15]:
import numpy as np
np.linspace(-10,10,10,dtype=int)

array([-10,  -8,  -6,  -4,  -2,   1,   3,   5,   7,  10])

In [16]:
import numpy as np
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

ARRAY ATTRIBUTES


In [17]:
import numpy as np
a1=np.arange(10)
a2=np.arange(12,dtype=float).reshape(3,4)
a3=np.arange(8).reshape(2,2,2)

a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
#ndim
a3.ndim

3

In [19]:
#shape
print(a3.shape)
a3

(2, 2, 2)


array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [20]:
#size
print(a2.size)
a2

12


array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [21]:
#itemsize
a3.itemsize

8

In [22]:
#dtype
print(a1.dtype)
print(a2.dtype)
print(a3.dtype)

int64
float64
int64


Changing Datatypes

In [23]:
#astyoe
a3.astype(np.int32)

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]], dtype=int32)

ARRAY OPERATIONS

In [24]:
a1 = np.arange(12).reshape(3,4)
a2 = np.arange(12,24).reshape(3,4)

a1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [25]:
#scaler operations

a1*2

array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22]])

In [26]:
#relational

a2 > 5

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [27]:
#vector operations

a1 + a2

array([[12, 14, 16, 18],
       [20, 22, 24, 26],
       [28, 30, 32, 34]])

ARRAY FUNCTIONS

In [28]:
import numpy as np
a1 = np.random.random((3,3))
a1 = np.round(a1*100)
a1

array([[75., 65., 22.],
       [70.,  9., 43.],
       [ 9., 10., 76.]])

In [29]:
#max/min/sum/prod
# 0 ->col and 1->row
np.max(a1,axis=0)

array([75., 65., 76.])

In [30]:
#mean/median/standard/var
np.var(a1,axis=1)

array([528.66666667, 622.88888889, 982.88888889])

In [31]:
# trignometry functions
np.sin(a1)

array([[-0.38778164,  0.82682868, -0.00885131],
       [ 0.77389068,  0.41211849, -0.83177474],
       [ 0.41211849, -0.54402111,  0.56610764]])

In [32]:
# dot product
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(12,24).reshape(4,3)

np.dot(a2,a3)

array([[114, 120, 126],
       [378, 400, 422],
       [642, 680, 718]])

Indexing and Slicing

In [33]:
import numpy as np
a1=np.arange(10)
a2=np.arange(12,dtype=float).reshape(3,4)
a3=np.arange(8).reshape(2,2,2)

a3


array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [34]:
a1[-1]

np.int64(9)

In [35]:
a2

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [36]:
a2[1,2]

np.float64(6.0)

In [37]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [38]:
a3[1,0,1]

np.int64(5)

In [39]:
a3[0,1,0]

np.int64(2)

In [40]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [41]:
a1[2:5:2]

array([2, 4])

In [42]:
a2

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [43]:
a2[0,:]

array([0., 1., 2., 3.])

In [44]:
a2[:,2]

array([ 2.,  6., 10.])

In [45]:
a2[1:,1:3]

array([[ 5.,  6.],
       [ 9., 10.]])

In [46]:
a2[::2,::3]

array([[ 0.,  3.],
       [ 8., 11.]])

In [47]:
a2[::2,1::2]

array([[ 1.,  3.],
       [ 9., 11.]])

In [48]:
a2[1,::3]

array([4., 7.])

In [49]:
a3 = np.arange(27).reshape(3,3,3)
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [50]:
a3[1]

array([[ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [51]:
a3[::2]

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [52]:
a3[::2,0,::2]

array([[ 0,  2],
       [18, 20]])

Iterating

In [53]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [54]:
a2

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [55]:
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [56]:
a1

for i in a1:
    print(i)

0
1
2
3
4
5
6
7
8
9


In [57]:
a2

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [58]:
for i in a2:
    print(i)

[0. 1. 2. 3.]
[4. 5. 6. 7.]
[ 8.  9. 10. 11.]


In [59]:
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [60]:
for i in a3:
    print(i)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[18 19 20]
 [21 22 23]
 [24 25 26]]


In [61]:
for i in np.nditer(a3):
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26


Reshaping

In [62]:
#transpose

np.transpose(a2)

array([[ 0.,  4.,  8.],
       [ 1.,  5.,  9.],
       [ 2.,  6., 10.],
       [ 3.,  7., 11.]])

In [63]:
#ravel

a2.ravel()

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])

Stacking

In [64]:
# horizontal stacking
a4 = np.arange(12).reshape(3,4)
a5 = np.arange(12,24).reshape(3,4)
a5

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [65]:
np.hstack((a4,a5))

array([[ 0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23]])

In [66]:
# vertical stacking
np.vstack((a4,a5))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

Spliting

In [67]:
# horizontal spliting
a4

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [68]:
np.hsplit(a4,4)

[array([[0],
        [4],
        [8]]),
 array([[1],
        [5],
        [9]]),
 array([[ 2],
        [ 6],
        [10]]),
 array([[ 3],
        [ 7],
        [11]])]

In [69]:
# vertical spliting
a5

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [70]:
np.vsplit(a5,3)

[array([[12, 13, 14, 15]]),
 array([[16, 17, 18, 19]]),
 array([[20, 21, 22, 23]])]

Numpy array vs Python lists

In [71]:
# speed
# list
a = [i for i in range(10000000)]
b = [i for i in range(10000000,20000000)]

c = []
import time

start = time.time()
for i in range(len(a)):
  c.append(a[i] + b[i])
print(time.time()-start)

3.6438605785369873


In [72]:
import numpy as np
a = np.arange(10000000)
b = np.arange(10000000,20000000)

start = time.time()
c = a+b
print(time.time()-start)

0.32349610328674316


In [73]:
#memory
a = [i for i in range(10000000)]
import sys

sys.getsizeof(a)

89095160

In [74]:
a = np.arange(10000000,dtype=np.int32)
sys.getsizeof(a)

40000112

Advanced Indexing

In [75]:
# Normal indexing and slicing
a = np.arange(12).reshape(4,3)
a


array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [76]:
a[1,2]

np.int64(5)

In [77]:
a[1:3,1:3]

array([[4, 5],
       [7, 8]])

In [78]:
# Fancy indexing
a[[0,2,3]]

array([[ 0,  1,  2],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [ ]:
# Boolean indexing